### ISSUE TITLE
How to control AWS IOT devices with Alexa？

### ISSUE THREAD

**Issue by InfiniteYuan1** [espressif/esp-aws-iot#11]
Hi，
I have encountered problems with controlling ESP32 via Alexa.

 - ESP32 accesses AWS IOT via aws-iot-device-sdk-embedded-C

Is there any way to control esp32 through alexa?

**Comment by shahpiyushv** [comment]
@InfiniteYuan1 , using AWS IoT with Alexa is not that straightforward. AWS IoT is just an MQTT broker. You need some additional logic on top of that to enable Alexa. There needs to be some user login mechanism, then some method to link an ESP32 with a given user and then an Alexa Smart Skill  to enable control via Alexa using the same user credentials (shared using OAUTH2), etc. Basically, it is not in the scope of this ESP AWS IoT Project.

Since this is not directly related to ESP AWS IoT, I think this issue can be closed.
