### ISSUE TITLE
Create automatically things and keys for devices (CA-143)

### ISSUE THREAD

**Issue by ESP3235** [espressif/esp-aws-iot#55]
Hi to all.
I want to create 1000 iot things in AWS and create private certificates and keys for each of them.
Is there a way to create automatically things and own keys with development tools?

I am created keys and certifications for sample iot thing and tested it. But for 1000 devices this method is time consuming.

Thanks a lot.

**Comment by shahpiyushv** [comment]
@ESP3235 , have you checked the concept of [Just in Time Provisioning](https://aws.amazon.com/blogs/iot/setting-up-just-in-time-provisioning-with-aws-iot-core/)? That may suit your purpose since all the keys and certificates can be generated on the host machine and you need to register just the CA certificate.
